[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip setuptools wheel",
  "python3 -m pip install -r chatbot-backend/requirements.txt"
]
