[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install --upgrade setuptools wheel", 
  "pip install flask flask-cors cohere pdfplumber numpy rouge bert-score"
]
